export const services = [
  {
    id: 1,
    title: 'Artículos Promocionales',
    description: 'Con más de 20 años de experiencia, somos expertos en ofrecer soluciones a medida para tu negocio.',
    image: '/images/promo.webp',
  },
  {
    id: 2,
    title: 'Signs / Letreros',
    description: 'Haz realidad tu visión con nuestros letreros personalizados, creados para destacar y atraer todas las miradas.',
    image: '/images/Store-sign.png',
  },
  {
    id: 3,
    title: 'Vehicle Wraps / Wraps para autos',
    description: 'Convierte tu vehículo en publicidad en movimiento: la visibilidad que tu negocio necesita en el camino.',
    image: '/images/car-wrap.webp',
  },
  {
    id: 4,
    title: 'Apparel / Ropa',
    description: 'Gorras, Camisetas, suéteres y más, manteniendo tu imagen a donde vayas.',
    image: '/images/apparel.webp',
  },
  {
    id: 5,
    title: 'Website Design',
    description: 'Haz que tu negocio destaque en internet con websites estáticos, fáciles de mantener y actualizar. Dale a tu marca la imagen profesional que merece y asegúrate de estar presente donde tus clientes te buscan.',
    image: '/images/website.webp',
  },
];

export const galleryImages = [
  '/images/promo-img-1.webp',
  '/images/promo-img-3.webp',
  '/images/promo-img-4.webp',
  '/images/promo-img-5.webp',
  '/images/promo-img-7.webp',
  '/images/promo-img-9.webp',
  '/images/promo-img-10.webp',
  '/images/promo-img-11.webp',
  '/images/promo-img-12.webp',
  '/images/promo-img-13.webp',
  '/images/promo-img-14.webp',
  '/images/promo-img-15.webp',
  '/images/promo-img-18.webp',
  '/images/promo-img-19.webp',
  '/images/promo-img-20.webp',
  '/images/promo-img-21.webp',
  '/images/promo-img-22.webp',
  '/images/promo-img-23.webp',
  '/images/promo-img-24.webp',
  '/images/promo-img-25.webp',
  '/images/promo-img-26.webp',
  '/images/promo-img-30.webp',
  '/images/promo-img-31.webp',
  '/images/promo-img-32.webp',
  '/images/promo-img-33.webp',
  '/images/promo-img-34.webp',
  '/images/promo-img-35.webp',
  '/images/promo-img-36.webp',
  '/images/promo-img-37.webp',
  '/images/promo-img-38.webp',
  '/images/promo-img-39.webp',
  '/images/promo-img-40.webp',
  '/images/promo-img-41.webp',
  '/images/promo-img-42.webp',
  '/images/promo-img-43.webp',
];

export const webWorks = [
  {
    id: 1,
    title: "Hector's Moving",
    description: "Hector & Sons Moving es una empresa familiar especializada en mudanzas y más. Nuestro equipo les ha creado un sitio web intuitivo y eficiente, destacando su mensaje claro y ofreciendo acceso rápido para contactarlos. Este sitio web está diseñado para proporcionar a sus clientes una experiencia de usuario fluida y directa, asegurando que puedan obtener la información y asistencia que necesitan de manera inmediata.",
    link: "https://www.hectorandsonsmoving.com",
    image: "/images/hector-web.webp",
  },
  {
    id: 2,
    title: "Granda Glass Corp.",
    description: "Granda Glass Corp. son expertos en todo lo relacionado con vidrios, incluyendo reparación e instalación. Hemos diseñado un sitio web intuitivo donde pueden mostrar su portafolio de trabajos, permitiendo a los clientes apreciar la calidad y la variedad de sus proyectos. El sitio está pensado para destacar la experiencia y profesionalismo de Granda Glass Corp., facilitando el acceso a información y servicios de manera eficiente.",
    link: null,
    image: "/images/glass-website.webp",
  },
  {
    id: 3,
    title: "Castro Pro Painting",
    description: "Castro Pro Painting provee servicios profesionales de pintura. El sitio web diseñado de manera personalizada refleja el excelente trabajo realizado por Castro Pro Painting, destacando su profesionalismo y calidad en cada proyecto. Nuestra plataforma permite a los clientes explorar fácilmente sus servicios y comprobar el alto estándar de sus trabajos anteriores.",
    link: null,
    image: "/images/android-phone.webp",
  }
];
